### ISSUE TITLE
return product info

### ISSUE THREAD

**Issue by brianyang** [rconnelly/shopnode#1]
Hi,

This is really cool, thanks for putting this together! could you explain how to get product info from shopify? Any help you could provide would be great, thanks!

**Comment by brianyang** [comment]
shopnode.products.getAll()

**Comment by rconnelly** [comment]
Hey sorry i didn't respond sooner. I've been out of town.

shopnode.products.getAll() should return all the products. 

There is also a concept of a "product variant".

After closer inspection, i notice that I'm currently not handling "Receive a single Product Variant". 

Is this what you need?
